version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20

  pre_build:
    commands:
      - echo "Starting PRE_BUILD phase..."
      - echo "Authenticating with Amazon ECR..."
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 888517278813.dkr.ecr.us-east-2.amazonaws.com

  build:
    commands:
      - echo "Starting BUILD phase..."
      - echo "Building the Docker application image..."
      - docker build -t goplan:latest .
      - docker tag goplan:latest 888517278813.dkr.ecr.us-east-2.amazonaws.com/goplan:$CODEBUILD_RESOLVED_SOURCE_VERSION

  post_build:
    commands:
      - echo "Starting POST_BUILD phase..."
      - echo "Pushing the Docker image to Amazon ECR..."
      - docker push 888517278813.dkr.ecr.us-east-2.amazonaws.com/goplan:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo "Writing imageDefinitions.json file..."
      - printf '[{"name":"prod-goplan","imageUri":"%s"}]' 888517278813.dkr.ecr.us-east-2.amazonaws.com/goplan:$CODEBUILD_RESOLVED_SOURCE_VERSION > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json