version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel
    ports:
      - '8000:80'  # Map host port 8000 to container port 80 (Nginx)
    command: /usr/bin/supervisord -c /etc/supervisord.conf
    depends_on:
      - db
    environment:
      APP_ENV: production
      APP_KEY: base64:kiCpf5exbizJaEQf9sS2EpV+y248D7ATxXNILUhScrw=
      DB_HOST: db
      DB_DATABASE: gp
      DB_USERNAME: root
      DB_PASSWORD: ''
      XDEBUG_MODE: off

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: gp
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - '8080:80'  # Changed to avoid conflict with app
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ''
    depends_on:
      - db
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
